import type { Metadata } from 'next';
import { Oswald, Roboto } from 'next/font/google';
import '@/shared/common/main-split.scss';

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['200', '700'],
  display: 'swap',
  variable: '--font-oswald',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['500', '700', '900'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oswald.variable} ${roboto.variable}`}>
      <body>{children}</body>
    </html>
  );
}
